version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
      POSTGRES_DB: news_pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Miniflux RSS Reader
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
      - BASE_URL=http://localhost:8080
      - POLLING_FREQUENCY=15
      - BATCH_SIZE=100
    depends_on:
      miniflux-db:
        condition: service_healthy
    restart: unless-stopped

  # Miniflux Database
  miniflux-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miniflux"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Stage-A Microservice
  stage-a:
    build:
      context: ./Stage-A_Microservice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_PRIMARY_URL=http://ollama:11434
      - OLLAMA_TIMEOUT=120
      - API_KEY=prod-key-2025
    depends_on:
      - ollama
    restart: unless-stopped

  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    # Note: You'll need to pull models after container starts:
    # docker exec -it ollama ollama pull llama3.2:1b
    # docker exec -it ollama ollama pull mistral:7b

  # News Pipeline Service
  pipeline:
    build:
      context: ./miniflux_news_pipeline
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://newsuser:newspass@postgres/news_pipeline
      - STAGE_A_URL=http://stage-a:5000
      - STAGE_A_API_KEY=prod-key-2025
      - OLLAMA_PRIMARY_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      stage-a:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  miniflux_data:
    driver: local
  ollama_data:
    driver: local

networks:
  default:
    driver: bridge